version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      - TZ=Asia/Tokyo
    env_file: .env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  # db-test:
  #   image: postgres:14
  #   env_file: ./.env.test.local
  #   ports:
  #     - 5433:5432
  #   networks:
  #     - backend

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file: .env.local
    environment:
      - TZ=Asia/Tokyo
    tty: true
    working_dir: /app
    # command: "npm run dev"
    command: "bash"
    ports: # Host:Container
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - next:/app/.next
    networks:
      - backend
    depends_on:
      - db
    restart: "always"

networks:
  backend:

volumes:
  pgdata:
  node_modules:
  next:
