steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/blitz-tutorial:$COMMIT_SHA",
        "-f",
        "docker/Dockerfile",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/blitz-tutorial:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "blitz-tutorial"
      - "--image"
      - "gcr.io/$PROJECT_ID/blitz-tutorial:$COMMIT_SHA"
      - "--region"
      - "us-west1"
images:
  - "gcr.io/$PROJECT_ID/blitz-tutorial:$COMMIT_SHA"
