#==================================================
# FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:16 AS base
FROM node:16-slim
WORKDIR /app
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && \
  apt-get install -y openssl git && \
  apt-get clean && rm -rf /var/lib/apt/lists/* && rm -rf /var/cache/debconf/*

COPY package.json package*.json ./
RUN npm install
COPY . .

RUN npx blitz prisma generate
CMD ["npm", "run", "dev"]


