version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      - TZ=Asia/Tokyo
    env_file: ../.env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: blitz-tutorial
    env_file: ../.env.local
    environment:
      - TZ=Asia/Tokyo
    tty: true
    working_dir: /app
    command: "bash"
    ports: # Host:Container
      - "3000:3000"
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

volumes:
  pgdata:
